---
- name: install apache & php
  hosts: lamp
  become: true
  tasks:
  - name: ensure apt cache is up to date
    apt: update_cache=yes

  - name: ensure packages are installed
    apt: pkg={{ item }} state=latest
    with_items:
     - apache2
     - libapache2-mod-php7.0
     - php7.0-fpm
     - php7.0-pgsql
     - php-xml
     - php7.0-gd
     - php7.0-mbstring
     - postgresql-client

  - name: Configure properly drupal.conf
    copy: >
      src=files/etc/apache2/sites-available/drupal.conf dest=/etc/apache2/sites-available/drupal.conf owner=www-data group=www-data mode=0755

  - name: habilitar drupal
    command: a2ensite drupal.conf

    notify:
      - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
