---
- name: Drupal installation
  hosts: lamp
  become: true
  tasks:
  - name: Descarga Drupal
    get_url: 
      url: https://ftp.drupal.org/files/projects/drupal-8.6.7.zip
      dest: /home/vagrant/drupal-8.6.7.zip

  - name: Unzip Drupal
    unarchive:
      src: /home/vagrant/drupal-8.6.7.zip
      dest: /var/www/html
      remote_src: yes
      owner: www-data
      group: www-data
      mode: 0644

  - name: Enable fast cgi
    command: a2enmod proxy_fcgi

  - name: Habilitamos la configuración de fpm
    command: a2enconf php7.0-fpm
    notify:
      - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
