---
- name: Create a PostgreSQL DB server
  hosts: dns
  become: true
  tasks:
  - name: ensure apt cache is up to date
    apt: update_cache=yes

  - name: ensure packages are installed
    apt: pkg={{item}}
    with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2

  - name: Ensure the PostgreSQL service is running
    service: name=postgresql state=started enabled=yes



  - name: PostgreSQL | Create new databases
    become: yes
    become_user: postgres
    vars:
      ansible_ssh_pipelining: true
    postgresql_db:
      name: newdb
      encoding: UTF-8

  - name: PostgreSQL Create database user
    become: yes
    become_user: postgres
    vars:
      ansible_ssh_pipelining: true
    postgresql_user:
      db: newdb
      name: luis
      password: luis
      priv: "ALL"
      expires: infinity

