---
- name: Create a PostgreSQL DB server
  hosts: dns
  become: true
  tasks:
  - name: ensure apt cache is up to date
    apt: update_cache=yes

  - name: ensure packages are installed
    apt: pkg={{item}}
    with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2

  - name: Ensure the PostgreSQL service is running
    service: name=postgresql state=started enabled=yes

  - name: config postgresql.conf
    copy: >
      src=files/etc/postgresql/postgresql.conf
      dest=/etc/postgresql/9.6/main/postgresql.conf

  - name: config pg_hba.conf
    copy: >
      src=files/etc/postgresql/pg_hba.conf
      dest=/etc/postgresql/9.6/main/pg_hba.conf

  - name: chmod and chown postgres files
    file:
      path: /etc/postgresql/9.6/main
      owner: postgres
      group: postgres
    with_items:
      - postgresql.conf
      - pg_hba.conf
  
    notify:
      - restart postgresql

  - name: PostgreSQL | Create new databases
    become: yes
    become_user: postgres
    vars:
      ansible_ssh_pipelining: true
    postgresql_db:
      name: newdb
      encoding: UTF-8

  - name: PostgreSQL Create database user
    become: yes
    become_user: postgres
    vars:
      ansible_ssh_pipelining: true
    postgresql_user:
      db: newdb
      name: luis2
      password: luis
      priv: "ALL"
      expires: infinity

    notify:
      - restart postgresql

  handlers:
    - name: restart postgresql
      command: systemctl restart postgresql

